=== sxdny/grado_superior/Asignaturas/Lenguaje de Marcas/XML/XSD/actividad2/apartado5/exercici5.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
<xs:annotation>
  <xs:documentation xml:lang="ca">
    Exercici6. Una empresa pretén guardar la informació dels seus empleats en xml. 
    Fes un esquema per poder modelar-ho creant nou tipus de dades. S'ha de guardar 
    el nom de l'empleat i un identificador únic com atribut, la data d'inici del contracte, 
    el lloc que ocupa i els llocs que ha ocupat, el seu cap directe com una relació amb l'ID, 
    el que cobra, tots els seus títol acadèmics, la seu en que treballa d'entre les 
    tres possibles Madrid, Barcelona, València; finalment s'ha de guardar un camp que 
    siguin observacions on també hi pot haver altres etiquetes com merits, demerits. 
    Fes també un document que s'hi ajusti amb al menys 5 empleats.
    Fe un captura de pantalla amb el document validat amb un validador.

  </xs:documentation>
</xs:annotation>

<xs:element name="empleats">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="empleat" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="dataInici">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="dia">
                    <xs:simpleType>
                      <xs:restriction base="xs:int">
                        <xs:maxInclusive value="31"></xs:maxInclusive>
                        <xs:minInclusive value="1"></xs:minInclusive>
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:element>
                  <xs:element name="mes">
                    <xs:simpleType>
                      <xs:restriction base="xs:int">
                        <xs:maxInclusive value="12"></xs:maxInclusive>
                        <xs:minInclusive value="1"></xs:minInclusive>
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:element>
                  <xs:element name="any">
                    <xs:simpleType>
                      <xs:restriction base="xs:int">
                        <xs:maxInclusive value="9999"></xs:maxInclusive>
                        <xs:minInclusive value="1000"></xs:minInclusive>
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:element>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
            <xs:element name="lloc" type="xs:string" minOccurs="0"></xs:element>
            <xs:element name="sou" type="xs:int" minOccurs="0"></xs:element>
            <xs:element name="titulacio" type="xs:string" maxOccurs="unbounded" minOccurs="0"></xs:element>
            <xs:element name="seu" type="xs:string" minOccurs="0"></xs:element>
            <xs:element name="lloc" type="xs:string" minOccurs="0"></xs:element>
            <xs:element name="llocPrevi" type="xs:string" minOccurs="0" maxOccurs="unbounded"></xs:element>
            <xs:element name="observacions" minOccurs="0"></xs:element>
          </xs:sequence>
          <xs:attribute name="codi" type="xs:string"></xs:attribute>
          <xs:attribute name="nom" type="xs:string"></xs:attribute>
          <xs:attribute name="cap" type="xs:string"></xs:attribute>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:element>



</xs:schema>

=== sxdny/grado_superior/asignaturas/ldm/work/xml/xsd/ac2_XSD/apartado5/exercici5.xml
<?xml version="1.0" encoding="UTF-8"?>
<empleats xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="exercici5.xsd">
  <empleat codi="x12323892s" nom="Jordi Bellvé Soler">
    <dataInici>
      <dia>01</dia>
      <mes>09</mes>
      <any>1987</any>
    </dataInici>
  <lloc>Propietari</lloc>
  <sou>5000</sou>
  <titulacio>Empresarials UAM</titulacio>
  <seu>Madrid</seu>
  </empleat>
  
  <empleat codi="x81753892p" nom="Isabel Bellvé Smith" cap="x12323892s">
    <dataInici>
      <dia>22</dia>
      <mes>12</mes>
      <any>2003</any>
    </dataInici>
  <lloc>Cap Barcelona</lloc>
  <sou>3200</sou>
  <titulacio>Economia UB</titulacio>
  <seu>Barcelona</seu>  
</empleat>

<empleat codi="x11766592t" nom="Ana Sort Llof" cap="x81753892p">
    <dataInici>
      <dia>22</dia>
      <mes>12</mes>
      <any>2000</any>
    </dataInici>
  <lloc>Secretaria de la cap de Barcelona</lloc>
  <sou>1100</sou>
  <titulacio>Batxillerat </titulacio>
  <titulacio>Técnico Gestión Administrativa</titulacio>
  <seu>Barcelona</seu>
  <llocPrevi>Secretaria de logística de Barcelona</llocPrevi>  
  <observacions>Disponibilitat de viatjar. Casada amb un fill. 
    <merit>Sol veure quan un negociador no diu la veritat </merit>
    <merit>Sol treballar molt ràpid i bé</merit>
    <demerit>Unes poques vegades, per motius aliens a la feina, ha estat molt agitada i nerviosa i no ha rendit bé</demerit>  
  </observacions>
</empleat>

<empleat codi="x51766502t" nom="Ramón Soltono Visalte" cap="x81753892p">
    <dataInici>
      <dia>10</dia>
      <mes>02</mes>
      <any>1999</any>
    </dataInici>
  <lloc>Operari de embalatge</lloc>
  <sou>600</sou>
  <titulacio>Tecnico en Embalaje</titulacio>
  <seu>Barcelona</seu> 
  <llocPrevi>Operari varis</llocPrevi>
  <llocPrevi>Encarregat de logística</llocPrevi> 
  <observacions>    
    <demerit>Si no hi ha algú que el vigila no treballa</demerit>  
  </observacions>
</empleat>

<empleat codi="x31766502t" nom="Amalia Dolita Tokil" cap="x81753892p">
    <dataInici>
      <dia>10</dia>
      <mes>10</mes>
      <any>2011</any>
    </dataInici>
  <lloc>Operari varis</lloc>
  <sou>950</sou>  
  
  <seu>Barcelona</seu>  
  
</empleat>



</empleats>
